[build]
command = "npm run build"
publish = "dist"

[[redirects]]
from = "/success"
to = "/contact?success=true"
status = 302

# Form handling error redirect
[[redirects]]
from = "/error"
to = "/success?error=true"
status = 302